// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRoles;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRoles;
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRoles = 'superuser' | 'admin' | 'user';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRoles;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginAccessTokenData = {
    body: Body_login_login_access_token;
};

export type LoginAccessTokenResponse = (Token);

export type LoginAccessTokenError = (HTTPValidationError);

export type TestTokenResponse = (UserPublic);

export type TestTokenError = unknown;

export type GetARecordData = {
    query: {
        domain: string;
    };
};

export type GetARecordResponse = (unknown);

export type GetARecordError = (HTTPValidationError);

export type GetPtrRecordData = {
    query: {
        ip: string;
    };
};

export type GetPtrRecordResponse = (unknown);

export type GetPtrRecordError = (HTTPValidationError);

export type GetZoneMasterFromDnsServersData = {
    query: {
        domain: string;
    };
};

export type GetZoneMasterFromDnsServersResponse = (unknown);

export type GetZoneMasterFromDnsServersError = (HTTPValidationError);

export type GetMxRecordData = {
    query: {
        domain: string;
    };
};

export type GetMxRecordResponse = (unknown);

export type GetMxRecordError = (HTTPValidationError);

export type GetNsRecordsData = {
    query: {
        domain: string;
    };
};

export type GetNsRecordsResponse = (unknown);

export type GetNsRecordsError = (HTTPValidationError);

export type ReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadUsersResponse = (UsersPublic);

export type ReadUsersError = (HTTPValidationError);

export type CreateUserData = {
    body: UserCreate;
};

export type CreateUserResponse = (UserPublic);

export type CreateUserError = (HTTPValidationError);

export type ReadUserMeResponse = (UserPublic);

export type ReadUserMeError = unknown;

export type DeleteUserMeResponse = (Message);

export type DeleteUserMeError = unknown;

export type UpdateUserMeData = {
    body: UserUpdateMe;
};

export type UpdateUserMeResponse = (UserPublic);

export type UpdateUserMeError = (HTTPValidationError);

export type UpdatePasswordMeData = {
    body: UpdatePassword;
};

export type UpdatePasswordMeResponse = (Message);

export type UpdatePasswordMeError = (HTTPValidationError);

export type RegisterUserData = {
    body: UserRegister;
};

export type RegisterUserResponse = (UserPublic);

export type RegisterUserError = (HTTPValidationError);

export type ReadUserByIdData = {
    path: {
        user_id: string;
    };
};

export type ReadUserByIdResponse = (UserPublic);

export type ReadUserByIdError = (HTTPValidationError);

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
};

export type UpdateUserResponse = (UserPublic);

export type UpdateUserError = (HTTPValidationError);

export type DeleteUserData = {
    path: {
        user_id: string;
    };
};

export type DeleteUserResponse = (Message);

export type DeleteUserError = (HTTPValidationError);

export type GetUserActionsData = {
    path: {
        user_id: string;
    };
};

export type GetUserActionsResponse = (unknown);

export type GetUserActionsError = (HTTPValidationError);

export type FindPleskSubscriptionByDomainData = {
    query: {
        domain: string;
    };
};

export type FindPleskSubscriptionByDomainResponse = (unknown);

export type FindPleskSubscriptionByDomainError = (HTTPValidationError);

export type HealthCheckResponse = (boolean);

export type HealthCheckError = unknown;