// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DeleteZonemasterLogSchema = {
    ip: IPv4Address;
    timestamp: string;
    domain: DomainName;
    current_zone_master: string;
    log_type: 'DELETE_ZONE_MASTER';
};

export type log_type = 'DELETE_ZONE_MASTER';

export type DomainARecordResponse = {
    domain: DomainName;
    records: Array<IPv4Address>;
};

export type DomainMxRecordResponse = {
    domain: DomainName;
    records: Array<DomainName>;
};

export type DomainName = {
    name: string;
};

export type DomainNsRecordResponse = {
    domain: DomainName;
    records: Array<DomainName>;
};

export type GetPleskLoginLinkLogSchema = {
    ip: IPv4Address;
    timestamp: string;
    plesk_server: PleskServerDomain;
    subscription_id: number;
    log_type: 'GET_SUBSCRIPTION_LOGIN_LINK';
    ssh_username: LinuxUsername;
};

export type log_type2 = 'GET_SUBSCRIPTION_LOGIN_LINK';

export type GetZoneMasterLogSchema = {
    ip: IPv4Address;
    timestamp: string;
    domain: DomainName;
    log_type: 'GET_ZONE_MASTER';
};

export type log_type3 = 'GET_ZONE_MASTER';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IPv4Address = {
    ip: string;
};

export type LinuxUsername = string;

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PaginatedUserLogListSchema = {
    total_count: number;
    page: number;
    page_size?: number;
    total_pages: number;
    data: Array<UserLogPublic>;
};

export type PleskServerDomain = {
    name: string;
};

export type SetZonemasterInput = {
    target_plesk_server: string;
    domain: string;
};

export type SetZoneMasterLogSchema = {
    ip: IPv4Address;
    timestamp: string;
    domain: DomainName;
    target_zone_master: PleskServerDomain;
    current_zone_master: (PleskServerDomain | null);
    log_type: 'SET_ZONE_MASTER';
};

export type log_type4 = 'SET_ZONE_MASTER';

export type SubscriptionDetailsModel = {
    host: DomainName;
    id: string;
    name: string;
    username: string;
    userlogin: string;
    domains: Array<SubscriptionName>;
    domain_states: Array<{
        [key: string]: (string);
    }>;
    is_space_overused: boolean;
    subscription_size_mb: number;
    subscription_status: string;
};

export type SubscriptionListResponseModel = Array<SubscriptionDetailsModel>;

export type SubscriptionLoginLinkInput = {
    host: string;
    subscription_id: number;
};

export type SubscriptionName = {
    name: string;
};

export type SuperUserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    ssh_username?: (string | null);
};

export type TestMailCredentials = {
    login_link: string;
    password: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserActionType = 'GET_ZONE_MASTER' | 'DELETE_ZONE_MASTER' | 'SET_ZONE_MASTER' | 'GET_SUBSCRIPTION_LOGIN_LINK' | 'PLESK_MAIL_GET_TEST_MAIL';

export type UserActivityLogFilterSchema = {
    ip?: (IPv4Address | null);
    timestamp?: (string | null);
    log_type?: (UserActionType | null);
    domain?: (DomainName | null);
    plesk_server?: (PleskServerDomain | null);
    subscription_id?: (number | null);
    ssh_username?: (LinuxUsername | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRoles;
    ssh_username?: (string | null);
    password: string;
};

export type UserLogPublic = {
    full_name?: (string | null);
    role?: UserRoles;
    ssh_username?: (string | null);
    id: string;
    details: (DeleteZonemasterLogSchema | SetZoneMasterLogSchema | GetZoneMasterLogSchema | GetPleskLoginLinkLogSchema);
};

export type UserLogSearchRequestSchema = {
    page?: number;
    page_size?: number;
    filters: UserActivityLogFilterSchema;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRoles;
    ssh_username?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRoles = 'superuser' | 'admin' | 'user';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRoles;
    ssh_username?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetARecordData = {
    query: {
        name: string;
    };
};

export type GetARecordResponse = (DomainARecordResponse);

export type GetARecordError = (HTTPValidationError);

export type GetPtrRecordData = {
    query: {
        ip: string;
    };
};

export type GetPtrRecordResponse = (unknown);

export type GetPtrRecordError = (HTTPValidationError);

export type GetZoneMasterFromDnsServersData = {
    query: {
        name: string;
    };
};

export type GetZoneMasterFromDnsServersResponse = (unknown);

export type GetZoneMasterFromDnsServersError = (HTTPValidationError);

export type DeleteZoneFileForDomainData = {
    query: {
        name: string;
    };
};

export type DeleteZoneFileForDomainResponse = (unknown);

export type DeleteZoneFileForDomainError = (HTTPValidationError);

export type GetMxRecordData = {
    query: {
        name: string;
    };
};

export type GetMxRecordResponse = (DomainMxRecordResponse);

export type GetMxRecordError = (HTTPValidationError);

export type GetNsRecordsData = {
    query: {
        name: string;
    };
};

export type GetNsRecordsResponse = (DomainNsRecordResponse);

export type GetNsRecordsError = (HTTPValidationError);

export type ReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ReadUsersResponse = (UsersPublic);

export type ReadUsersError = (HTTPValidationError);

export type CreateUserData = {
    body: UserCreate;
};

export type CreateUserResponse = (UserPublic);

export type CreateUserError = (HTTPValidationError);

export type ReadUserMeResponse = (UserPublic);

export type ReadUserMeError = unknown;

export type DeleteUserMeResponse = (Message);

export type DeleteUserMeError = unknown;

export type UpdateUserMeData = {
    body: UserUpdateMe;
};

export type UpdateUserMeResponse = (UserPublic);

export type UpdateUserMeError = (HTTPValidationError);

export type UpdatePasswordMeData = {
    body: UpdatePassword;
};

export type UpdatePasswordMeResponse = (Message);

export type UpdatePasswordMeError = (HTTPValidationError);

export type RegisterUserData = {
    body: UserRegister;
};

export type RegisterUserResponse = (UserPublic);

export type RegisterUserError = (HTTPValidationError);

export type ReadUserByIdData = {
    path: {
        user_id: string;
    };
};

export type ReadUserByIdResponse = (UserPublic);

export type ReadUserByIdError = (HTTPValidationError);

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
};

export type UpdateUserResponse = (UserPublic);

export type UpdateUserError = (HTTPValidationError);

export type DeleteUserData = {
    path: {
        user_id: string;
    };
};

export type DeleteUserResponse = (Message);

export type DeleteUserError = (HTTPValidationError);

export type GetOwnActionsData = {
    body: UserLogSearchRequestSchema;
};

export type GetOwnActionsResponse = (PaginatedUserLogListSchema);

export type GetOwnActionsError = (HTTPValidationError);

export type GetUserActionsData = {
    path: {
        user_id: string;
    };
};

export type GetUserActionsResponse = (unknown);

export type GetUserActionsError = (HTTPValidationError);

export type UpdateSuperuserMeData = {
    body: SuperUserUpdateMe;
};

export type UpdateSuperuserMeResponse = (UserPublic);

export type UpdateSuperuserMeError = (HTTPValidationError);

export type FindPleskSubscriptionByDomainData = {
    query: {
        name: string;
    };
};

export type FindPleskSubscriptionByDomainResponse = (SubscriptionListResponseModel);

export type FindPleskSubscriptionByDomainError = (HTTPValidationError);

export type GetSubscriptionLoginLinkData = {
    body: SubscriptionLoginLinkInput;
};

export type GetSubscriptionLoginLinkResponse = (unknown);

export type GetSubscriptionLoginLinkError = (HTTPValidationError);

export type SetZonemasterData = {
    body: SetZonemasterInput;
};

export type SetZonemasterResponse = (Message);

export type SetZonemasterError = (HTTPValidationError);

export type CreateTestmailForDomainData = {
    query: {
        maildomain: string;
        server: string;
    };
};

export type CreateTestmailForDomainResponse = (TestMailCredentials);

export type CreateTestmailForDomainError = (HTTPValidationError);

export type SharePublicKeyResponse = (unknown);

export type SharePublicKeyError = unknown;

export type GetTokenData = {
    query: {
        command: string;
    };
};

export type GetTokenResponse = (unknown);

export type GetTokenError = (HTTPValidationError);

export type HealthCheckResponse = (boolean);

export type HealthCheckError = unknown;

export type RecoverPasswordData = {
    path: {
        email: string;
    };
};

export type RecoverPasswordResponse = (Message);

export type RecoverPasswordError = (HTTPValidationError);

export type ResetPasswordData = {
    body: NewPassword;
};

export type ResetPasswordResponse = (Message);

export type ResetPasswordError = (HTTPValidationError);

export type RecoverPasswordHtmlContentData = {
    path: {
        email: string;
    };
};

export type RecoverPasswordHtmlContentResponse = (string);

export type RecoverPasswordHtmlContentError = (HTTPValidationError);

export type LoginAccessTokenData = {
    body: Body_login_login_access_token;
};

export type LoginAccessTokenResponse = (Token);

export type LoginAccessTokenError = (HTTPValidationError);

export type TestTokenResponse = (UserPublic);

export type TestTokenError = unknown;